import json
import os

pasta = "./Acordaos"
for root, dirs, arquivo in os.walk(pasta):
    arquivos = arquivo
campos = {}
print(arquivos)
i = 0
# print_memory()
for arquivo in arquivos:
    print(os.path.join(root, arquivo))
    print("A realizar Teste ", i)
    i += 1
    f = open(os.path.join(root, arquivo))
    acordaos = json.load(f)
    for acordao in acordaos:
        for key in acordao:
            if key == "Informação Auxiliar":
                pass
            elif key not in campos and not isinstance(acordao[key], dict):
                if isinstance(acordao[key], list):
                    campos[key] = ["String"]
                else:
                    campos[key] = "String"
            elif isinstance(acordao[key], dict):
                if key not in campos:
                    campos[key] = dict()
                for elem in acordao[key]:
                    if elem not in campos[key]:
                        if isinstance(acordao[key], list):
                            campos[key][elem] = ["String"]
                        else:
                            campos[key][elem] = "String"
                # elif arquivo not in campos[key][elem]:
                # campos[key][elem].append(arquivo)
            # elif arquivo not in campos[key]:
            # campos[key].append(arquivo)
    del acordaos
    f.close()
print(campos)
print(len(campos))

"""
campos = {
    "Processo": "jtre_acordaos.json",
    "Relator": "jtre_acordaos.json",
    "Descritores": "jtre_acordaos.json",
    "Data do Acordão": "jtre_acordaos.json",
    "Votação": "jtre_acordaos.json",
    "Sumário": "jtre_acordaos.json",
    "Decisão Texto Integral": "jtre_acordaos.json",
    "url": "jtre_acordaos.json",
    "tribunal": "jtre_acordaos.json",
    "Decisão": "jtre_acordaos.json",
    "Meio Processual": "jtre_acordaos.json",
    "Legislação Nacional": "jtre_acordaos.json",
    "Área Temática 1": "jtre_acordaos.json",
    "Referências Internacionais": "jtre_acordaos.json",
    "Jurisprudência Nacional": "jtre_acordaos.json",
    "Legislação Comunitária": "jtre_acordaos.json",
    "Jurisprudência Internacional": "jtre_acordaos.json",
    "Tribunal Recorrido": "jtre_acordaos.json",
    "Legislação Estrangeira": "jtre_acordaos.json",
    "Processo no Tribunal Recorrido": "jtre_acordaos.json",
    "Referência Processo": "jtre_acordaos.json",
    "Indicações Eventuais": "jtre_acordaos.json",
    "Nº Convencional": "jcon_acordaos.json",
    "Nº do Documento": "jcon_acordaos.json",
    "Recorrente": "jcon_acordaos.json",
    "Recorrido 1": "jcon_acordaos.json",
    "Recorrido 2": "jcon_acordaos.json",
    "Data de Entrada": "jcon_acordaos.json",
    "Objecto": "jcon_acordaos.json",
    "Área Temática 2": "jcon_acordaos.json",
    "Doutrina": "jcon_acordaos.json",
    "Recusa Aplicação": "jcon_acordaos.json",
    "Referência a Pareceres": "jcon_acordaos.json",
    "Ano da Publicação": "jcon_acordaos.json",
    "Privacidade": "jcon_acordaos.json",
    "Apêndice": "jcon_acordaos.json",
    "Data do Apêndice": "jcon_acordaos.json",
    "1ª Pág. de Publicação do Acordão": "jcon_acordaos.json",
    "Referências Publicação": "jcon_acordaos.json",
    "Reclamações": "jtrp_acordaos.json",
    "Apenso": "jtrp_acordaos.json",
    "Data Dec. Recorrida": "jtrp_acordaos.json",
    "Recurso": "jtrp_acordaos.json",
    "Juízo ou Secção": "jsta_acordaos.json",
    "Tribunal": "jsta_acordaos.json",
    "Informação Auxiliar": "jsta_acordaos.json",
    "Nº do Volume": "jsta_acordaos.json",
    "Jurisprudência Estrangeira": "jsta_acordaos.json",
    "Página": "jsta_acordaos.json",
    "Parecer Ministério Publico": "jtcn_acordaos.json",
    "Contencioso": "jtcampc(a|t)_acordaos.json",
    "Nº Processo/TAF": "jtcampc(a|t)_acordaos.json",
    "Observações": "jtcampc(a|t)_acordaos.json",
    "Peça Processual": "jtcampc(a|t)_acordaos.json",
    "Tema": "jtcampc(a|t)_acordaos.json",
    "Nº Único do Processo": "jtrl_acordaos.json",
    "Acordão": "atco1_acordaos.json",
    "Espécie": "atco1_acordaos.json",
    "Requerente": "atco1_acordaos.json",
    "Requerido": "atco1_acordaos.json",
    "Normas Apreciadas": "atco1_acordaos.json",
    "Normas Julgadas Inconst.": "atco1_acordaos.json",
    "Volume dos Acordãos do T.C.": "atco1_acordaos.json",
    "Constituição": "atco1_acordaos.json",
    "Nº do Diário da República": "atco1_acordaos.json",
    "Série do Diário da República": "atco1_acordaos.json",
    "Data do Diário da República": "atco1_acordaos.json",
    "Página do Diário da República": "atco1_acordaos.json",
    "Nº do Boletim do M.J.": "atco1_acordaos.json",
    "Página do Boletim do M.J.": "atco1_acordaos.json",
    "Jurisprudência Constitucional": "atco1_acordaos.json",
    "Normas Suscitadas": "atco1_acordaos.json",
    "Declaração de Voto": "atco1_acordaos.json",
    "Voto Vencido": "atco1_acordaos.json",
    "Normas Declaradas Inconst.": "atco1_acordaos.json",
    "Página do Volume": "atco1_acordaos.json",
    "Outra Jurisprudência": "atco1_acordaos.json",
    "Tribunal 1ª instância": "jdgpj_acordaos.json",
    "Tipo de Ação": "jdgpj_acordaos.json",
    "Tipo de Contrato": "jdgpj_acordaos.json",
    "Autor": "jdgpj_acordaos.json",
    "Réu": "jdgpj_acordaos.json",
    "Data da Decisão": "jdgpj_acordaos.json",
    "Texto das Cláusulas Abusivas": "jdgpj_acordaos.json",
    "Data do Acórdão": "jdgpj_acordaos.json",
}
print(len(campos))
"""

campos1 = {
    "Processo": [
        "jtre_acordaos.json",
        "jcon_acordaos.json",
        "jtrp_acordaos.json",
        "jsta_acordaos.json",
        "jtcn_acordaos.json",
        "jtcampc(a|t)_acordaos.json",
        "jtrc_acordaos.json",
        "jtrl_acordaos.json",
        "jtrg_acordaos.json",
        "atco1_acordaos.json",
        "jstj_acordaos.json",
        "jtca_acordaos.json",
        "jdgpj_acordaos.json",
    ],
    "Relator": [
        "jtre_acordaos.json",
        "jcon_acordaos.json",
        "jtrp_acordaos.json",
        "jsta_acordaos.json",
        "jtcn_acordaos.json",
        "jtcampc(a|t)_acordaos.json",
        "jtrc_acordaos.json",
        "jtrl_acordaos.json",
        "jtrg_acordaos.json",
        "atco1_acordaos.json",
        "jstj_acordaos.json",
        "jtca_acordaos.json",
        "jdgpj_acordaos.json",
    ],
    "Descritores": [
        "jtre_acordaos.json",
        "jcon_acordaos.json",
        "jtrp_acordaos.json",
        "jsta_acordaos.json",
        "jtcn_acordaos.json",
        "jtcampc(a|t)_acordaos.json",
        "jtrc_acordaos.json",
        "jtrl_acordaos.json",
        "jtrg_acordaos.json",
        "atco1_acordaos.json",
        "jstj_acordaos.json",
        "jtca_acordaos.json",
        "jdgpj_acordaos.json",
    ],
    "Data do Acordão": [
        "jtre_acordaos.json",
        "jcon_acordaos.json",
        "jtrp_acordaos.json",
        "jsta_acordaos.json",
        "jtcn_acordaos.json",
        "jtcampc(a|t)_acordaos.json",
        "jtrc_acordaos.json",
        "jtrl_acordaos.json",
        "jtrg_acordaos.json",
        "atco1_acordaos.json",
        "jstj_acordaos.json",
        "jtca_acordaos.json",
        "jdgpj_acordaos.json",
    ],
    "Votação": [
        "jtre_acordaos.json",
        "jcon_acordaos.json",
        "jtrp_acordaos.json",
        "jsta_acordaos.json",
        "jtcn_acordaos.json",
        "jtrc_acordaos.json",
        "jtrl_acordaos.json",
        "jtrg_acordaos.json",
        "atco1_acordaos.json",
        "jstj_acordaos.json",
        "jtca_acordaos.json",
    ],
    "Sumário": [
        "jtre_acordaos.json",
        "jtrp_acordaos.json",
        "jsta_acordaos.json",
        "jtcn_acordaos.json",
        "jtrc_acordaos.json",
        "jtrl_acordaos.json",
        "jtrg_acordaos.json",
        "atco1_acordaos.json",
        "jstj_acordaos.json",
        "jtca_acordaos.json",
    ],
    "Decisão Texto Integral": [
        "jtre_acordaos.json",
        "jcon_acordaos.json",
        "jtrp_acordaos.json",
        "jsta_acordaos.json",
        "jtcn_acordaos.json",
        "jtrc_acordaos.json",
        "jtrl_acordaos.json",
        "jtrg_acordaos.json",
        "atco1_acordaos.json",
        "jstj_acordaos.json",
        "jtca_acordaos.json",
        "jdgpj_acordaos.json",
    ],
    "tribunal": [
        "jtre_acordaos.json",
        "jcon_acordaos.json",
        "jtrp_acordaos.json",
        "jsta_acordaos.json",
        "jtcn_acordaos.json",
        "jtcampc(a|t)_acordaos.json",
        "jtrc_acordaos.json",
        "jtrl_acordaos.json",
        "jtrg_acordaos.json",
        "atco1_acordaos.json",
        "jstj_acordaos.json",
        "jtca_acordaos.json",
        "jdgpj_acordaos.json",
    ],
    "Decisão": [
        "jtre_acordaos.json",
        "jcon_acordaos.json",
        "jtrp_acordaos.json",
        "jsta_acordaos.json",
        "jtcn_acordaos.json",
        "jtrc_acordaos.json",
        "jtrl_acordaos.json",
        "jtrg_acordaos.json",
        "atco1_acordaos.json",
        "jstj_acordaos.json",
        "jtca_acordaos.json",
        "jdgpj_acordaos.json",
    ],
    "Meio Processual": [
        "jtre_acordaos.json",
        "jcon_acordaos.json",
        "jtrp_acordaos.json",
        "jsta_acordaos.json",
        "jtcn_acordaos.json",
        "jtrc_acordaos.json",
        "jtrl_acordaos.json",
        "jtrg_acordaos.json",
        "jstj_acordaos.json",
        "jtca_acordaos.json",
    ],
    "Legislações": [
        "jtre_acordaos.json",
        "jcon_acordaos.json",
        "jtrp_acordaos.json",
        "jsta_acordaos.json",
        "jtcn_acordaos.json",
        "jtrc_acordaos.json",
        "jtrl_acordaos.json",
        "jtrg_acordaos.json",
        "atco1_acordaos.json",
        "jstj_acordaos.json",
    ],
    "Área Temática 1": [
        "jtre_acordaos.json",
        "jcon_acordaos.json",
        "jtrp_acordaos.json",
        "jsta_acordaos.json",
        "jtcampc(a|t)_acordaos.json",
        "jtrc_acordaos.json",
        "jtrl_acordaos.json",
        "jtrg_acordaos.json",
        "atco1_acordaos.json",
        "jstj_acordaos.json",
    ],
    "Referências Internacionais": [
        "jtre_acordaos.json",
        "jcon_acordaos.json",
        "jtrp_acordaos.json",
        "jsta_acordaos.json",
        "jtrl_acordaos.json",
        "atco1_acordaos.json",
        "jstj_acordaos.json",
    ],
    "Jurisprudências": [
        "jtre_acordaos.json",
        "jcon_acordaos.json",
        "jtrp_acordaos.json",
        "jsta_acordaos.json",
        "jtrc_acordaos.json",
        "jtrl_acordaos.json",
        "jtrg_acordaos.json",
        "atco1_acordaos.json",
        "jstj_acordaos.json",
    ],
    "Tribunal Recorrido": [
        "jtre_acordaos.json",
        "jtrp_acordaos.json",
        "jtrc_acordaos.json",
        "jtrl_acordaos.json",
        "jstj_acordaos.json",
    ],
    "Processo no Tribunal Recorrido": [
        "jtre_acordaos.json",
        "jtrp_acordaos.json",
        "jtrc_acordaos.json",
        "jtrl_acordaos.json",
        "jstj_acordaos.json",
    ],
    "Referência Processo": [
        "jtre_acordaos.json",
        "jtrp_acordaos.json",
        "jtrl_acordaos.json",
        "jstj_acordaos.json",
    ],
    "Indicações Eventuais": [
        "jtre_acordaos.json",
        "jcon_acordaos.json",
        "jtrp_acordaos.json",
        "jsta_acordaos.json",
        "jtcn_acordaos.json",
        "jtrc_acordaos.json",
        "jtrl_acordaos.json",
        "atco1_acordaos.json",
        "jstj_acordaos.json",
    ],
    "Nº Convencional": [
        "jcon_acordaos.json",
        "jtrp_acordaos.json",
        "jsta_acordaos.json",
        "jtcn_acordaos.json",
        "jtrc_acordaos.json",
        "jtrl_acordaos.json",
        "jtrg_acordaos.json",
        "atco1_acordaos.json",
        "jstj_acordaos.json",
        "jtca_acordaos.json",
    ],
    "Nº do Documento": [
        "jcon_acordaos.json",
        "jtrp_acordaos.json",
        "jsta_acordaos.json",
        "jtrc_acordaos.json",
        "jtrl_acordaos.json",
        "jtrg_acordaos.json",
        "atco1_acordaos.json",
        "jstj_acordaos.json",
    ],
    "Requerente": [
        "jcon_acordaos.json",
        "jsta_acordaos.json",
        "jtcn_acordaos.json",
        "atco1_acordaos.json",
        "jdgpj_acordaos.json",
    ],
    "Requerido": [
        "jcon_acordaos.json",
        "jsta_acordaos.json",
        "jtcn_acordaos.json",
        "atco1_acordaos.json",
        "jdgpj_acordaos.json",
    ],
    "Data de Entrada": [
        "jcon_acordaos.json",
        "jsta_acordaos.json",
        "jtcn_acordaos.json",
        "jtcampc(a|t)_acordaos.json",
        "jtrl_acordaos.json",
        "jstj_acordaos.json",
    ],
    "Objecto": ["jcon_acordaos.json", "jsta_acordaos.json", "jtcn_acordaos.json"],
    "Área Temática 2": [
        "jcon_acordaos.json",
        "jsta_acordaos.json",
        "atco1_acordaos.json",
    ],
    "Doutrina": ["jcon_acordaos.json", "jsta_acordaos.json", "jstj_acordaos.json"],
    "Recusa Aplicação": ["jcon_acordaos.json", "jsta_acordaos.json"],
    "Referência a Pareceres": [
        "jcon_acordaos.json",
        "jsta_acordaos.json",
        "atco1_acordaos.json",
    ],
    "Privacidade": [
        "jcon_acordaos.json",
        "jtrp_acordaos.json",
        "jsta_acordaos.json",
        "jtrc_acordaos.json",
        "jtrl_acordaos.json",
        "jtrg_acordaos.json",
        "atco1_acordaos.json",
        "jstj_acordaos.json",
    ],
    "Apêndice": ["jcon_acordaos.json", "jsta_acordaos.json"],
    "Data do Apêndice": ["jcon_acordaos.json", "jsta_acordaos.json"],
    "1ª Pág. de Publicação do Acordão": ["jcon_acordaos.json", "jsta_acordaos.json"],
    "Referências Publicação": [
        "jcon_acordaos.json",
        "jtrp_acordaos.json",
        "jsta_acordaos.json",
        "jtrc_acordaos.json",
        "jtrl_acordaos.json",
        "atco1_acordaos.json",
        "jstj_acordaos.json",
    ],
    "Reclamações": ["jtrp_acordaos.json"],
    "Apenso": [
        "jtrp_acordaos.json",
        "jtcn_acordaos.json",
        "jtrl_acordaos.json",
        "jstj_acordaos.json",
    ],
    "Data da Decisão": ["jtrp_acordaos.json", "jdgpj_acordaos.json"],
    "Recurso": [
        "jtrp_acordaos.json",
        "jtrl_acordaos.json",
        "jstj_acordaos.json",
        "jdgpj_acordaos.json",
    ],
    "Juízo ou Secção": [
        "jsta_acordaos.json",
        "jtcn_acordaos.json",
        "jtcampc(a|t)_acordaos.json",
        "jtrg_acordaos.json",
        "jtca_acordaos.json",
        "jdgpj_acordaos.json",
    ],
    "Informação Auxiliar": [
        "jsta_acordaos.json",
        "jtcn_acordaos.json",
        "jtrl_acordaos.json",
        "jstj_acordaos.json",
        "jtca_acordaos.json",
    ],
    "Tribunal": ["jsta_acordaos.json", "jtcn_acordaos.json", "jdgpj_acordaos.json"],
    "Nº do Volume": ["jsta_acordaos.json", "jtcn_acordaos.json"],
    "Página": ["jsta_acordaos.json"],
    "Parecer Ministério Publico": ["jtcn_acordaos.json"],
    "Nº Processo/TAF": ["jtcampc(a|t)_acordaos.json"],
    "Observações": ["jtcampc(a|t)_acordaos.json"],
    "Peça Processual": ["jtcampc(a|t)_acordaos.json"],
    "Nº Único do Processo": ["jtrl_acordaos.json", "jstj_acordaos.json"],
    "Acordão": ["atco1_acordaos.json"],
    "Espécie": ["atco1_acordaos.json"],
    "Normas Apreciadas": ["atco1_acordaos.json"],
    "Normas Julgadas Inconst.": ["atco1_acordaos.json"],
    "Volume dos Acordãos do T.C.": ["atco1_acordaos.json"],
    "Constituição": ["atco1_acordaos.json"],
    "Nº do Diário da República": ["atco1_acordaos.json"],
    "Série do Diário da República": ["atco1_acordaos.json"],
    "Data do Diário da República": ["atco1_acordaos.json"],
    "Página do Diário da República": ["atco1_acordaos.json"],
    "Nº do Boletim do M.J.": ["atco1_acordaos.json"],
    "Página do Boletim do M.J.": ["atco1_acordaos.json"],
    "Normas Suscitadas": ["atco1_acordaos.json"],
    "Declaração de Voto": ["atco1_acordaos.json"],
    "Voto Vencido": ["atco1_acordaos.json"],
    "Normas Declaradas Inconst.": ["atco1_acordaos.json"],
    "Página do Volume": ["atco1_acordaos.json"],
    "Tipo de Ação": ["jdgpj_acordaos.json"],
    "Tipo de Contrato": ["jdgpj_acordaos.json"],
    "Texto das Cláusulas Abusivas": ["jdgpj_acordaos.json"],
}






keys = [
    "1ª Pág. de Publicação do Acordão",
    "Nº do Volume",
    "Página",
    "Parecer Ministério Público",
    "Nº Processo/TAF",
    "Observações",
    "Peça Processual",
    "Nº Único do Processo",
    "Acórdão",
    "Espécie",
    "Normas Apreciadas",
    "Normas Julgadas Inconst.",
    "Volume dos Acórdãos do T.C.",
    "Constituição",
    "Nº do Diário da República",
    "Série do Diário da República",
    "Data do Diário da República",
    "Página do Diário da República",
    "Nº do Boletim do M.J.",
    "Página do Boletim do M.J.",
    "Normas Suscitadas",
    "Declaração de Voto",
    "Voto Vencido",
    "Normas Declaradas Inconst.",
    "Página do Volume",
    "Tipo de Ação",
    "Tipo de Contrato",
    "Texto das Cláusulas Abusivas",
]
